#!/bin/sh
echo -e "           ___
           (.· |   $USER\033[31m@\033[0m$(uname -n)
           (<> |   \033[31mos: \033[0m$(uname -o)
          / __  \  \033[31march: \033[0m$(uname -m)
         ( /  \ /| \033[31mkernel: \033[0m$(uname -s)
        _/\ __)/_) \033[31mversion: \033[0m$(uname -v)
        \/-____\/  $([ -f /proc/cpuinfo ] && echo -e '\033[31mcpu:\033[0m' \033[0m$(cat /proc/cpuinfo | grep "model name" | awk '{print $4, $5, $6, $7, $8, $9, $10, $11, $12}' | head -n1))
                   \033[31mposixfetch: \033[0m1.0
        "
